// packages/vue/src/components/InfiniteList.vue
d<script setup lang="ts" generic="T">
import { computed, onMounted } from "vue";
import { findMissingPages } from "@scrolloop/shared";
import type { PageResponse, Range } from "@scrolloop/shared";
import VirtualList from "./VirtualList.vue";
import { useInfinitePages } from "../composables/useInfinitePages";

const props = withDefaults(
  defineProps<{
    fetchPage: (page: number, size: number) => Promise<PageResponse<T>>;
    itemSize: number;
    pageSize?: number;
    initialPage?: number;
    prefetchThreshold?: number;
    height?: number;
    overscan?: number;
    class?: string;
  }>(),
  {
    pageSize: 20,
    initialPage: 0,
    prefetchThreshold: 1,
    height: 400,
  }
);

const emit = defineEmits<{
  pageLoad: [page: number, items: T[]];
  error: [error: Error];
}>();

const overscan = computed(
  () => props.overscan ?? Math.max(20, props.pageSize * 2)
);

const { pages, loadingPages, total, hasMore, error, loadPage, retry } =
  useInfinitePages<T>(() => ({
    fetchPage: props.fetchPage,
    pageSize: props.pageSize,
    initialPage: props.initialPage,
    onPageLoad: (page, items) => emit("pageLoad", page, items),
    onError: (err) => emit("error", err),
  }));

onMounted(() => {
  const needed = Math.ceil(props.height / props.itemSize) + overscan.value * 2;
  const count = Math.ceil(needed / props.pageSize) + props.prefetchThreshold;
  for (let p = 0; p < count; p++) loadPage(p);
});

function handleRangeChange(range: Range) {
  const ps = (range.startIndex / props.pageSize) | 0;
  const pe =
    ((range.endIndex / props.pageSize) | 0) +
    props.prefetchThreshold +
    Math.ceil(overscan.value / props.pageSize);
  const missingPages = findMissingPages(ps, pe, pages.value, loadingPages.value);
  for (const p of missingPages) loadPage(p);
}
</script>

<template>
  <div :style="{ height: `${height}px` }">
    <template v-if="error && total === 0">
      <slot name="error" :error="error" :retry="retry">
        <div class="scrolloop-state-container">
          <div class="scrolloop-error-content">
            <p class="scrolloop-error-message">Error: {{ error.message }}</p>
            <button class="scrolloop-retry-button" @click="retry">Retry</button>
          </div>
        </div>
      </slot>
    </template>

    <template v-else-if="total === 0 && loadingPages.size">
      <slot name="loading">
        <div class="scrolloop-state-container">
          <p class="scrolloop-state-text">Loading...</p>
        </div>
      </slot>
    </template>

    <template v-else-if="total === 0 && !hasMore">
      <slot name="empty">
        <div class="scrolloop-state-container">
          <p class="scrolloop-state-text">No data.</p>
        </div>
      </slot>
    </template>

    <VirtualList
      v-else
      :count="total"
      :item-size="itemSize"
      :height="height"
      :overscan="overscan"
      :class="$props.class"
      @range-change="handleRangeChange"
    >
      <template #default="{ index, style }">
        <slot
          :item="pages.get(Math.floor(index / props.pageSize))?.[index % props.pageSize]"
          :index="index"
          :style="style"
        />
      </template>
    </VirtualList>
  </div>
</template>

<style>
.scrolloop-state-container {
  height: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
}

.scrolloop-error-content {
  text-align: center;
}

.scrolloop-error-message {
  margin: 0 0 8px;
}

.scrolloop-retry-button {
  padding: 4px 12px;
  cursor: pointer;
}

.scrolloop-state-text {
  margin: 0;
}
</style>

// packages/react/src/components/InfiniteList.tsx
import { useEffect, memo } from "react";
import type { InfiniteListProps } from "../types";
import { VirtualList } from "./VirtualList";
import { useInfinitePages, findMissingPages } from "@scrolloop/shared";

function InfiniteListInner<T>(props: InfiniteListProps<T>) {
  const {
    fetchPage,
    renderItem,
    itemSize,
    pageSize = 20,
    initialPage = 0,
    prefetchThreshold = 1,
    height = 400,
    overscan: userOverscan,
    className,
    style,
    renderLoading,
    renderError,
    renderEmpty,
    onPageLoad,
    onError,
  } = props;

  const overscan = userOverscan ?? Math.max(20, pageSize * 2);

  const { allItems, pages, loadingPages, hasMore, error, loadPage, retry } =
    useInfinitePages({
      fetchPage,
      pageSize,
      initialPage,
      onPageLoad,
      onError,
    });

  useEffect(() => {
    if (pages.size === 0 && !error) {
      const totalNeededItems = Math.ceil(height / itemSize) + overscan * 2;
      for (
        let page = 0;
        page < Math.ceil(totalNeededItems / pageSize) + prefetchThreshold;
        page++
      )
        loadPage(page);
    }
  }, [
    pages.size,
    loadPage,
    initialPage,
    error,
    height,
    itemSize,
    pageSize,
    prefetchThreshold,
    overscan,
  ]);

  const handleRangeChange = (range: {
    startIndex: number;
    endIndex: number;
  }) => {
    const prefetchStart = Math.max(
      0,
      Math.floor(range.startIndex / pageSize) -
        Math.floor(range.endIndex / pageSize)
    );
    const prefetchEnd =
      Math.floor(range.endIndex / pageSize) +
      prefetchThreshold +
      Math.ceil(overscan / pageSize);

    findMissingPages(prefetchStart, prefetchEnd, pages, loadingPages);

    for (let page = prefetchStart; page <= prefetchEnd; page++) {
      loadPage(page);
    }
  };

  if (error && allItems.length === 0) {
    if (renderError)
      return <div style={{ height }}>{renderError(error, retry)}</div>;
    return (
      <div
        style={{
          height,
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
        }}
      >
        <div style={{ textAlign: "center" }}>
          <p>Error.</p>
          <p style={{ color: "#666", fontSize: "0.9em" }}>{error.message}</p>
          <button
            onClick={retry}
            style={{ marginTop: 8, padding: "4px 12px", cursor: "pointer" }}
          >
            Retry
          </button>
        </div>
      </div>
    );
  }

  if (allItems.length === 0 && loadingPages.size > 0) {
    if (renderLoading) {
      return <div style={{ height }}>{renderLoading()}</div>;
    }
    return (
      <div
        style={{
          height,
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
        }}
      >
        <p>Loading...</p>
      </div>
    );
  }

  if (allItems.length === 0 && !hasMore) {
    if (renderEmpty) {
      return <div style={{ height }}>{renderEmpty()}</div>;
    }
    return (
      <div
        style={{
          height,
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
        }}
      >
        <p>No data.</p>
      </div>
    );
  }

  return (
    <VirtualList
      count={allItems.length}
      itemSize={itemSize}
      height={height}
      overscan={overscan}
      className={className}
      style={style}
      onRangeChange={handleRangeChange}
      renderItem={(index, itemStyle) => {
        const item = allItems[index];
        return renderItem(item, index, itemStyle);
      }}
    />
  );
}

export const InfiniteList = memo(InfiniteListInner) as <T>(
  props: InfiniteListProps<T>
) => JSX.Element;
