// packages/svelte/src/VirtualList.svelte
<script lang="ts" generics="T">
  import { calculateVirtualRange } from "@scrolloop/core";
  import type { Snippet } from "svelte";

  interface Props {
    count: number;
    itemSize: number;
    height?: number;
    overscan?: number;
    onRangeChange?: (range: { startIndex: number; endIndex: number }) => void;
    children: Snippet<[index: number, style: Record<string, string>]>;
  }

  let {
    count,
    itemSize,
    height = 400,
    overscan = 4,
    onRangeChange,
    children,
  }: Props = $props();

  let containerEl: HTMLDivElement | undefined = $state();
  let scrollTop = $state(0);
  let prevScrollTop = $state(0);

  const totalHeight = $derived(count * itemSize);

  const range = $derived(
    calculateVirtualRange(
      scrollTop,
      height,
      itemSize,
      count,
      overscan,
      prevScrollTop
    )
  );

  const virtualItems = $derived.by(() => {
    const items: Array<{ index: number; style: Record<string, string> }> = [];
    for (let i = range.renderStart; i <= range.renderEnd; i++) {
      items.push({
        index: i,
        style: {
          position: "absolute",
          top: `${i * itemSize}px`,
          left: "0",
          right: "0",
          height: `${itemSize}px`,
        },
      });
    }
    return items;
  });

  $effect(() => {
    onRangeChange?.({
      startIndex: range.renderStart,
      endIndex: range.renderEnd,
    });
  });

  $effect(() => {
    const el = containerEl;
    if (!el) return;

    let prev = el.scrollTop;

    function handleScroll() {
      const next = el.scrollTop;
      prevScrollTop = prev;
      scrollTop = next;
      prev = next;
    }

    el.addEventListener("scroll", handleScroll, { passive: true });
    return () => el.removeEventListener("scroll", handleScroll);
  });
</script>

<div
  bind:this={containerEl}
  role="list"
  style:overflow="auto"
  style:height="{height}px"
  style:position="relative"
>
  <div
    style:position="relative"
    style:height="{totalHeight}px"
    style:width="100%"
  >
    {#each virtualItems as item (item.index)}
      <div role="listitem">
        {@render children(item.index, item.style)}
      </div>
    {/each}
  </div>
</div>

// packages/react/src/components/VirtualList.tsx
import {
  useEffect,
  useRef,
  useState,
  memo,
  useCallback,
  cloneElement,
  isValidElement,
  type CSSProperties,
} from "react";
import { flushSync } from "react-dom";
import type { VirtualListProps, ItemProps } from "../types";
import { calculateVirtualRange } from "@scrolloop/core";

export const VirtualList = memo<VirtualListProps>(
  ({
    count,
    itemSize,
    renderItem,
    height = 400,
    overscan = 4,
    className,
    style,
    onRangeChange,
  }) => {
    const containerRef = useRef<HTMLDivElement>(null);
    const scrollTopRef = useRef(0);
    const prevScrollTopRef = useRef(0);
    const [, forceUpdate] = useState(0);
    const prevRangeRef = useRef<{ start: number; end: number }>({
      start: -1,
      end: -1,
    });

    const totalHeight = count * itemSize;

    const scrollTop = scrollTopRef.current;
    const prevScrollTop = prevScrollTopRef.current;

    const { renderStart: renderStartIndex, renderEnd: renderEndIndex } =
      calculateVirtualRange(
        scrollTop,
        height,
        itemSize,
        count,
        overscan,
        prevScrollTop
      );

    useEffect(() => {
      if (
        onRangeChange &&
        (prevRangeRef.current.start !== renderStartIndex ||
          prevRangeRef.current.end !== renderEndIndex)
      ) {
        prevRangeRef.current = {
          start: renderStartIndex,
          end: renderEndIndex,
        };
        onRangeChange({
          startIndex: renderStartIndex,
          endIndex: renderEndIndex,
        });
      }
    }, [renderStartIndex, renderEndIndex, onRangeChange]);

    const handleScroll = useCallback(() => {
      const container = containerRef.current;
      if (!container) return;

      prevScrollTopRef.current = scrollTopRef.current;
      scrollTopRef.current = container.scrollTop;

      flushSync(() => {
        forceUpdate((prev) => prev + 1);
      });
    }, []);

    useEffect(() => {
      const container = containerRef.current;
      if (!container) return;

      container.addEventListener("scroll", handleScroll, { passive: true });

      return () => {
        container.removeEventListener("scroll", handleScroll);
      };
    }, [handleScroll]);

    const items = [];
    for (let i = renderStartIndex; i <= renderEndIndex; i++) {
      const itemStyle: CSSProperties = {
        position: "absolute",
        top: i * itemSize,
        left: 0,
        right: 0,
        height: itemSize,
      };

      const itemContent = renderItem(i, itemStyle);

      if (isValidElement(itemContent)) {
        items.push(
          cloneElement(itemContent, {
            key: i,
            role: "listitem",
          } as ItemProps)
        );
      }
    }

    return (
      <div
        ref={containerRef}
        role="list"
        className={className}
        style={{
          overflow: "auto",
          height,
          ...style,
        }}
      >
        <div
          style={{
            position: "relative",
            height: totalHeight,
            width: "100%",
          }}
        >
          {items}
        </div>
      </div>
    );
  }
);

VirtualList.displayName = "VirtualList";
