// packages/vue/src/components/VirtualList.vue
<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted, watch } from "vue";
import { calculateVirtualRange } from "scrolloop";
import type { Range } from "scrolloop";

const props = withDefaults(
  defineProps<{
    count: number;
    itemSize: number;
    height?: number;
    overscan?: number;
    class?: string;
  }>(),
  { height: 400, overscan: 4 }
);

const emit = defineEmits<{
  rangeChange: [range: Range];
}>();

const containerRef = ref<HTMLDivElement | null>(null);
const scrollTop = ref(0);
const prevScrollTop = ref(0);

const totalHeight = computed(() => props.count * props.itemSize);

const range = computed(() =>
  calculateVirtualRange(
    scrollTop.value,
    props.height,
    props.itemSize,
    props.count,
    props.overscan,
    prevScrollTop.value
  )
);

const virtualItems = computed(() => {
  const items: Array<{ index: number; style: Record<string, string> }> = [];
  for (let i = range.value.renderStart; i <= range.value.renderEnd; i++) {
    items.push({
      index: i,
      style: {
        position: "absolute",
        top: `${i * props.itemSize}px`,
        left: "0",
        right: "0",
        height: `${props.itemSize}px`,
      },
    });
  }
  return items;
});

watch(range, (r) => {
  emit("rangeChange", { startIndex: r.renderStart, endIndex: r.renderEnd });
});

function handleScroll() {
  const el = containerRef.value;
  if (!el) return;
  prevScrollTop.value = scrollTop.value;
  scrollTop.value = el.scrollTop;
}

onMounted(() => {
  containerRef.value?.addEventListener("scroll", handleScroll, {
    passive: true,
  });
});

onUnmounted(() => {
  containerRef.value?.removeEventListener("scroll", handleScroll);
});
</script>

<template>
  <div
    ref="containerRef"
    role="list"
    :class="$props.class"
    :style="{ overflow: 'auto', height: `${height}px` }"
  >
    <div
      :style="{
        position: 'relative',
        height: `${totalHeight}px`,
        width: '100%',
      }"
    >
      <template v-for="item in virtualItems" :key="item.index">
        <slot :index="item.index" :style="item.style" />
      </template>
    </div>
  </div>
</template>

// packages/preact/src/components/VirtualList.tsx
import {
  useRef,
  useState,
  useEffect,
  useCallback,
  useMemo,
} from "preact/hooks";
import type { CSSProperties } from "preact";
import { calculateVirtualRange } from "scrolloop";
import type { VirtualListProps } from "../types";

export function VirtualList({
  count,
  itemSize,
  renderItem,
  height = 400,
  overscan = 4,
  class: className,
  style,
  onRangeChange,
}: VirtualListProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  const scrollTopRef = useRef(0);
  const prevScrollTopRef = useRef(0);
  const onRangeChangeRef = useRef(onRangeChange);
  const [, forceUpdate] = useState(0);
  const prevRangeRef = useRef({ start: -1, end: -1 });

  useEffect(() => {
    onRangeChangeRef.current = onRangeChange;
  }, [onRangeChange]);

  const totalHeight = count * itemSize;

  const { renderStart, renderEnd } = calculateVirtualRange(
    scrollTopRef.current,
    height,
    itemSize,
    count,
    overscan,
    prevScrollTopRef.current
  );

  useEffect(() => {
    const cb = onRangeChangeRef.current;
    if (
      cb &&
      (prevRangeRef.current.start !== renderStart ||
        prevRangeRef.current.end !== renderEnd)
    ) {
      prevRangeRef.current = { start: renderStart, end: renderEnd };
      cb({ startIndex: renderStart, endIndex: renderEnd });
    }
  }, [renderStart, renderEnd]);

  const handleScroll = useCallback(() => {
    const el = containerRef.current;
    if (!el) return;
    prevScrollTopRef.current = scrollTopRef.current;
    scrollTopRef.current = el.scrollTop;
    forceUpdate((n) => n + 1);
  }, []);

  useEffect(() => {
    const el = containerRef.current;
    if (!el) return;
    el.addEventListener("scroll", handleScroll, { passive: true });
    return () => el.removeEventListener("scroll", handleScroll);
  }, [handleScroll]);

  const items = useMemo(() => {
    const result = [];
    for (let i = renderStart; i <= renderEnd; i++) {
      const itemStyle: CSSProperties = {
        position: "absolute",
        top: i * itemSize,
        left: 0,
        right: 0,
        height: itemSize,
      };
      result.push(
        <div key={i} role="listitem">
          {renderItem(i, itemStyle)}
        </div>
      );
    }
    return result;
  }, [renderStart, renderEnd, itemSize, renderItem]);

  const containerStyle: CSSProperties = {
    overflow: "auto",
    height,
    ...style,
  };

  return (
    <div
      ref={containerRef}
      role="list"
      class={className}
      style={containerStyle}
    >
      <div style={{ position: "relative", height: totalHeight, width: "100%" }}>
        {items}
      </div>
    </div>
  );
}
